services:
  - name: dashboard-app
    type: web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - fromGroup: dashboard-common
