-- AlterTable
ALTER TABLE "AP_Report" ALTER COLUMN "StartDate" DROP NOT NULL,
ALTER COLUMN "EndDate" DROP NOT NULL,
ALTER COLUMN "TimesheetApprovalDate" DROP NOT NULL,
ALTER COLUMN "VendorInvoiceDate" DROP NOT NULL,
ALTER COLUMN "PaymentDueDate" DROP NOT NULL;
